/** User-facing names for task fields shared by interactive surfaces. */
export const TASK_FIELD_LABELS = {
	TITLE: "Title",
	DESCRIPTION: "Description",
	STATUS: "Status",
	PRIORITY: "Priority",
	PROJECT: "Project",
	ASSIGNEE: "Assignee",
	REPORTER: "Reporter",
	LABELS: "Labels",
	TYPE: "Type",
	MILESTONE: "Milestone",
	DUE: "Due",
	DEPENDENCIES: "Dependencies",
	REFERENCES: "References",
	MODIFIED_FILES: "Modified files",
	ACCEPTANCE_CRITERIA: "Acceptance Criteria",
	DEFINITION_OF_DONE: "Definition of Done",
	IMPLEMENTATION_PLAN: "Implementation Plan",
	IMPLEMENTATION_NOTES: "Implementation Notes",
	FINAL_SUMMARY: "Final Summary",
} as const;
